factorytest:
  testcase:
    - {
        id: 0,
        name: WLAN0,
        command: ifconfig eth0,
        type: automatic,
        result: &ipregex '\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b',
      }
    - {
        id: 1,
        name: WLAN1,
        command: ifconfig eth1,
        type: automatic,
        result: *ipregex,
      }
    - {
        id: 2,
        name: WIFI,
        command: "/tmp/FactoryTest_WIFI.sh QYTECH qytech1688",
        type: automatic,
        result: 'WIFITest=\[OK\]',
      }
    - {
        id: 3,
        name: BT,
        command: blueman-browse,
        type: manual,
        result: 'hci\d+.*(?:\S{2}:){5}\S{2}',
      }
    - {
        id: 4,
        name: USB,
        command: "/tmp/FactoryTest_Storage.sh usb",
        type: automatic,
        result: 'USBTest=\[Ok\]',
      }
    - {
        id: 5,
        name: 4G,
        command: "/tmp/FactoryTest_Serial 4G",
        type: automatic,
        result: '4GTest=\[OK\]',
      }
    - {
        id: 6,
        name: SD,
        command: "/tmp/FactoryTest_Storage.sh sdcard",
        type: automatic,
        result: 'SdcardTest=\[Ok\]',
      }
    - {
        id: 7,
        name: Microphone,
        command: "arecord -Dhw:1,0 -d 5 -f cd -r 44100 -c 2 -t wav /tmp/test.wav; aplay -D plughw:1,0 /tmp/test.wav",
        type: manual,
        result: "",
      }
    - {
        id: 8,
        name: Speaker,
        command: "aplay -D plughw:1,0 /tmp/factory_test.wav",
        type: manual,
        result: "",
      }
    - {
        id: 9,
        name: RTC,
        command: "/tmp/FactoryTest_Rtc.sh",
        type: automatic,
        result: 'RTCTest=\[OK\]',
      }
    - {
        id: 10,
        name: GPS,
        command: "/tmp/FactoryTest_Serial GPS",
        type: automatic,
        result: 'GPSTest=\[OK\]',
      }
    - {
        id: 11,
        name: SN,
        command: "/tmp/FactoryTest_SN",
        type: display,
        result: "",
      }
  selected:
    - SN
    - WLAN0
    - WLAN1
    - WIFI
    - BT
    - USB
    - SD
    - 4G
    - GPS
    - Microphone
    - Speaker
    - RTC

agingtest:
  time: 4
  testcase:
    - {
        id: 0,
        name: cpu,
        enable: true,
        command: "echo $(cat /sys/class/thermal/thermal_zone0/temp /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq)",
      }
    - {
        id: 1,
        name: memory,
        enable: true,
        # command: "stressapptest -M 128 -s 120 -m 1",
        command: "/tmp/memtester_64bit 1G",
      }
    - {
        id: 2,
        name: vpu,
        enable: true,
        command: "gst-play-1.0 /media/root/*/SampleVideo_1280x720_5mb.mp4",
      }
    - { id: 3, name: gpu, enable: true, command: "test_glmark2.sh" }
